[build]
  base = "packages/web"
  publish = "dist"
  command = "npm run build"

# Redirect API calls to your backend (force HTTPS)
[[redirects]]
  from = "/api/*"
  to = "https://slimthicc-yt-api-latest.onrender.com/api/:splat"
  status = 200
  force = true
  # Allow Netlify to override response headers from origin
  responseOverrideAllowed = true
  # Add CORS headers to fix CORS issues
  [redirects.headers]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Origin, X-Requested-With, Content-Type, Accept, Authorization"
    Access-Control-Max-Age = "86400"

# Handle OPTIONS preflight requests for API
[[redirects]]
  from = "/api/*"
  to = "https://slimthicc-yt-api-latest.onrender.com/api/:splat"
  status = 200
  force = true
  # Only apply this rule for OPTIONS requests
  conditions = {method = "OPTIONS"}
  # Add CORS headers
  [redirects.headers]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Origin, X-Requested-With, Content-Type, Accept, Authorization"
    Access-Control-Max-Age = "86400"
    Content-Type = "text/plain"
    Content-Length = "0"

# Handle WebSocket connections (force WSS)
[[redirects]]
  from = "/ws/*"
  to = "wss://slimthicc-yt-api-latest.onrender.com/ws/:splat"
  status = 101
  force = true

# Handle SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Force HTTPS for all requests
[[headers]]
  for = "/*"
  [headers.values]
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "upgrade-insecure-requests" 