[build]
  base = "packages/web"
  publish = "dist"
  command = "npm run build"

# Redirect API calls to your backend
[[redirects]]
  from = "/api/*"
  to = "https://slimthicc-yt-api-latest.onrender.com/api/:splat"
  status = 200
  force = true

# Handle SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 