[build]
  base = "packages/web"
  publish = "dist"
  command = "npm run build"

# Handle OPTIONS preflight requests - these must come before other redirects
[[redirects]]
  from = "/api/*"
  to = "https://slimthicc-yt.onrender.com/api/:splat"
  status = 204
  force = true
  methods = ["OPTIONS"]
  [redirects.headers]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Origin, X-Requested-With, Content-Type, Accept, Authorization"
    Access-Control-Max-Age = "86400"
    Content-Type = "text/plain"
    Content-Length = "0"

# Redirect API calls to your backend (force HTTPS)
[[redirects]]
  from = "/api/*"
  to = "https://slimthicc-yt.onrender.com/api/:splat"
  status = 200
  force = true
  # Add proxy option for CORS handling
  responseOverrideAllowed = true
  # Add CORS headers to fix CORS issues
  [redirects.headers]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Origin, X-Requested-With, Content-Type, Accept, Authorization"
    Access-Control-Max-Age = "86400"
    X-Origin-Server = "Netlify"

# Handle SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Force HTTPS for all requests
[[headers]]
  for = "/*"
  [headers.values]
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "upgrade-insecure-requests" 