services:
  - type: web
    name: slimthicc_yt
    runtime: python
    buildCommand: cd server && pip install -r requirements.txt && bash setup.sh
    startCommand: cd server && gunicorn -k uvicorn.workers.UvicornWorker run:app --bind 0.0.0.0:$PORT