services:
  - type: web
    name: slimthicc_yt
    runtime: python
    buildCommand: pip install -r requirements.txt && chmod +x setup.sh && ./setup.sh
    startCommand: >
      cd server && 
      PATH="$HOME/.ffmpeg-downloader/bin:$PATH" 
      gunicorn -k uvicorn.workers.UvicornWorker src.main:app --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"